services:
  - type: web
    name: whatsapp-bot
    env: node
    plan: free
    branch: main
    buildCommand: "npm install"
    startCommand: "node serve.js"
    envVars:
      - key: NODE_ENV
        value: production
